---
# Source: conjur-config-namespace-prep/templates/conjur_connect_configmap.yaml
# The Conjur Connection ConfigMap contains references to Conjur credentials,
# taken from the "Golden ConfigMap". These can be used to enable Conjur
# authentication for applications to retrieve secrets securely.
apiVersion: v1
kind: ConfigMap
metadata:
  name: conjur-connect
  labels:
    app.kubernetes.io/name: "conjur-connect-configmap"
    app.kubernetes.io/instance: "conjur-default-configmap"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-connect-configmap"
data:
  CONJUR_ACCOUNT: conjur_account
  CONJUR_APPLIANCE_URL: https://conjur-dev-leader.gcloud101.com
  CONJUR_AUTHN_URL: https://conjur-dev-leader.gcloud101.com/authn-k8s/dev-cluster
  CONJUR_SSL_CERTIFICATE: |- 
    -----BEGIN CERTIFICATE-----
    MIIDtzCCAp+gAwIBAgIVAKSACrIpmFLFuY1wGWg3Z4O+MeiIMA0GCSqGSIb3DQEB
    CwUAMFcxFzAVBgNVBAoMDmNvbmp1cl9hY2NvdW50MRIwEAYDVQQLDAlDb25qdXIg
    Q0ExKDAmBgNVBAMMH2Nvbmp1ci1kZXYtbGVhZGVyLmdjbG91ZDEwMS5jb20wHhcN
    MjUxMTIyMDcwNzMzWhcNMzUxMTIwMDcwNzMzWjAqMSgwJgYDVQQDDB9jb25qdXIt
    ZGV2LWxlYWRlci5nY2xvdWQxMDEuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEAwW3v5PB4aDoOJibJue7ZGhhhhqHezTPNGapy7tj0kzWvbwCqCZXt
    XouJ+0vtjnW6Mw2XoWsJTbfvBNs+4QOxq9Ig1LwO2jH9yJsDg4S2yTYt95aSubHO
    KZoFLDvbAC1Ze9Y/d/cLrp2KeFWtQqN2b52Ek6nbshZ3RDHyWdgcPzk1VOwz/XzG
    PgJQkOoyhj7NWNSClY4tXwSLMwj0aBlW8c6qS8lige93BXgv1nPNvWCokBA/hP37
    QwLR1GgEdJOvHzYij2FZwAS67Ka5lrgEaHaCWNAag4GizT1q4i6AiLBwLV74a7XW
    lYAbBSlo+Br7Cv1usvdmlewjnH4WfkM8QwIDAQABo4GmMIGjMA4GA1UdDwEB/wQE
    AwIFoDAdBgNVHQ4EFgQU2jmj7l5rSw0yVb/vlWAYkK/YBwkwcgYDVR0RBGswaYIf
    Y29uanVyLWRldi1sZWFkZXIuZ2Nsb3VkMTAxLmNvbYIWY29uanVyMDEuZ2Nsb3Vk
    MTAxLmNvbYIWY29uanVyMDIuZ2Nsb3VkMTAxLmNvbYIWY29uanVyMDMuZ2Nsb3Vk
    MTAxLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAEwSd94IQeMhquX3Q1+497EJzm0Po
    trOdimX2zgTkI3RVjmMgktcN6QSCTdqr9ALhJrGJZP30ParXcgrkicwvZi5P5I5x
    p/4Ivb52ksI/xpcd3aWo6BF6sAqOsep+WjW56KfFjfMuPji/Ca4N5PPdttJqGeJo
    HfSuUsPVGKoovn8dLCeHypUDb9IjalLAO+j9GTzqHbv3Yu+e1TrPe8DU7dlBYXPM
    YFCNTLiHhZLia9EixO+BdrnuAu95sdMw2ppfsmWy1YWbCdJPIPLPqG/FGfYViPqu
    lTKzFCBg5+OcPCpLPJMYd+4DsgNW2kKcYSH+oBhz/jqDlsJjgy3QHE9bMQ==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEDzCCAvegAwIBAgIUXe1ZIZw69HYKZRNlpsaEa5O+EccwDQYJKoZIhvcNAQEL
    BQAwVzEXMBUGA1UECgwOY29uanVyX2FjY291bnQxEjAQBgNVBAsMCUNvbmp1ciBD
    QTEoMCYGA1UEAwwfY29uanVyLWRldi1sZWFkZXIuZ2Nsb3VkMTAxLmNvbTAeFw0y
    NTExMjIwNzA3MjJaFw0zNTExMjAwNzA3MjJaMFcxFzAVBgNVBAoMDmNvbmp1cl9h
    Y2NvdW50MRIwEAYDVQQLDAlDb25qdXIgQ0ExKDAmBgNVBAMMH2Nvbmp1ci1kZXYt
    bGVhZGVyLmdjbG91ZDEwMS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQCayiFVWGj+weIJ7r9e2gH1VLoTJmZ/XiXoTpVt5nI5UVpAkoZVb7mq19HE
    GbfwgBzAoEW/WpYEwuHTa+ofYSTBiqMcHXFfl8XzEYH6/TJlgBmRhZBjGZkWlJsJ
    EV6kqT3aQxMkOAR4t1xXsi6rPqB2g9Caf//0Ru5UwVab4AetGLLQyXl1Js3i+wb3
    meypPlUN5qiC63WSbl/OOV4rM3I55IYU32naw6uyuJDPFDqOmrEhQQS8bG9xFx4o
    QDADtBkB47lDHlcKTi/wNZ+eAdkx0jW7Ff6CUiUZN9UjmjqYUCkAkSuak4edboOM
    D7qOqS5OsHjQ+Nrp6jxDk35YHZnTAgMBAAGjgdIwgc8wcgYDVR0RBGswaYIfY29u
    anVyLWRldi1sZWFkZXIuZ2Nsb3VkMTAxLmNvbYIWY29uanVyMDEuZ2Nsb3VkMTAx
    LmNvbYIWY29uanVyMDIuZ2Nsb3VkMTAxLmNvbYIWY29uanVyMDMuZ2Nsb3VkMTAx
    LmNvbTAdBgNVHQ4EFgQU3Vro4NfaUvMOlBnt8oRfqdpuFVAwHwYDVR0jBBgwFoAU
    3Vro4NfaUvMOlBnt8oRfqdpuFVAwDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMCAeYw
    DQYJKoZIhvcNAQELBQADggEBAHFamuyI6HzLssSWPP0mm/QcPTlzo5ArP/jdrHAS
    gJ6NsgIxGHHhaIwYi3N5cCvUwxQcAaZOVHzffQSH7tnRBlKd8tFC6IbhlTXSiAsZ
    u1Hf6U2ugfC7pmAZXF1xlcS7M8qU1AiDgn/cOP058/RFc7OfQIKgTpnIvWrt+LYl
    OtcxbGvyQ4IClKtp6jvFQlQumVLNHN88M02PwLFjMqbiUjIdp0BHFwg7mNGuzzHd
    Z2ktAJbB4Hux6W+hfytOEdvkFl2rDNrNaboIbCu/j+FU732wLSkOhcNjfF/1C7rE
    RsF5JhYXmQbQ+vHOoUIJ9BO1KWRiG+soDzWNPRL7/4EwTVE=
    -----END CERTIFICATE-----
  CONJUR_AUTHENTICATOR_ID: dev-cluster